### ISSUE TITLE
Provide ability use {:array, inner_type}

### ISSUE THREAD

**Issue by chancs84** [chrisjowen/AutoSwaggerEx#1]
Auto Swagger restrict me to use only the {:array, map}, If I want to use {:array, integer} it treated as string, ` defp convert_type(type) do
    case type do
      :id -> "integer"
      Elixir.Comeonin.Ecto.Password -> "string"
      :naive_datetime -> "string"
      {:array, :map} -> "array"
      _ -> Atom.to_string(type)
    end
  end`

{:array, :integer} is considered as Atom.to_string(type)
`      {:array, :map} -> "array"
` this has to {:array, inner_type} -> "array

**Comment by chrisjowen** [comment]
Should be resolved in https://github.com/chrisjowen/AutoSwaggerEx/commit/29e6f78ecf47ca1d08565e601416fd574d4ddacf
